package ru.ticketcraft.saga;

public enum OrderSagaStatus {

    WAITING_FOR_RESERVATION,
    WAITING_FOR_PAYMENT,
    WAITING_FOR_TICKET_CONFIRMATION,
    COMPENSATING_RESERVATION,
    COMPLETED,
    FAILED
}
