spring:
  application:
    name: notification-service

  profiles:
    default: local

  server:
    port: ${SERVER_PORT:8083}
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
    "[ru.ticketcraft]": INFO
