spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false

ticketcraft:
  kafka:
    topic:
      partitions: 1
      replicas: 1

logging:
  level:
    "[ru.ticketcraft]": DEBUG
