spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: ${CATALOG_DB_USERNAME:postgres}
    password: ${CATALOG_DB_PASSWORD:postgres}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000
      validation-timeout: 1000

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

ticketcraft:
  kafka:
    consumer:
      concurrency: 1

    topic:
      partitions: 1
      replicas: 1

logging:
  level:
    "[ru.ticketcraft]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE
