spring:
  application:
    name: catalog-service

  profiles:
    default: local

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    "[ru.ticketcraft]": INFO
