spring:
  datasource:
    url: ${CATALOG_DB_URL}
    username: ${CATALOG_DB_USERNAME}
    password: ${CATALOG_DB_PASSWORD}

    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:30}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:3000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT_MS:1000}

  data:
    redis:
      url: ${REDIS_URL}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

ticketcraft:
  kafka:
    consumer:
      concurrency: ${CATALOG_KAFKA_CONCURRENCY:3}

    topic:
      partitions: ${KAFKA_TOPIC_PARTITIONS:3}
      replicas: ${KAFKA_TOPIC_REPLICAS:3}

logging:
  level:
    root: INFO
    "[ru.ticketcraft]": INFO
    "[org.hibernate.SQL]": OFF
    "[org.hibernate.orm.jdbc.bind]": OFF
