server:
  port: 8081 # Порт, на котором будет работать сервис каталога

spring:
  application:
    name: catalog-service

  # Активируем Виртуальные потоки (Virtual Threads)
  # В Spring Boot 4 это переводит сервер Tomcat на легковесные потоки Java 21+
#  threads:
#    virtual:
#      enabled: true

  # Настройка пула и подключения к PostgreSQL (контейнер "postgres-catalog" из docker-compose)
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: catalog_user
    password: catalog_password
    driver-class-name: org.postgresql.Driver
    # Настройки встроенного пула HikariCP
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  # Конфигурация JPA / Hibernate (под стандарты Jakarta EE 11)
  jpa:
    open-in-view: false # Важно: Выключаем Open-In-View для защиты пула соединений при высоких нагрузках
    defer-datasource-initialization: true # Гарантирует запуск data.sql ПОСЛЕ создания таблиц Hibernate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # create-drop: удаляет и создает таблицы заново при каждом запуске (идеально для тестов N+1)
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        # Форматирование SQL в консоли для удобного чтения запросов
        "[format_sql]": true
        "[use_sql_comments]": true

  sql:
    init:
      mode: always

# Включаем логирование SQL-запросов, чтобы увидеть проблему N+1 своими глазами
logging:
  level:
    root: INFO
    "[org.hibernate.SQL]": DEBUG # Показывает сами генерируемые SQL-запросы
    "[org.hibernate.orm.results]": TRACE # Показывает, как Hibernate маппит строки в Java-объекты

