<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Ссылка на родительский проект -->
    <parent>
        <groupId>ru.ticketcraft</groupId>
        <artifactId>ticket-craft-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath> <!-- Путь к корневому файлу -->
    </parent>

    <artifactId>common-dto</artifactId>
    <packaging>jar</packaging>

    <name>TicketCraft :: Common DTO</name>
    <description>Общие классы данных и событий</description>

	<properties>
    	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <!-- Новые координаты Jackson 3 -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>

</project>
