spring:
  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}

    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:30}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:3000}

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    producer:
      acks: all
      enable-idempotence: true
      retries: ${KAFKA_PRODUCER_RETRIES:10}


catalog:
  client:
    base-url: ${CATALOG_SERVICE_URL}

logging:
  level:
    root: INFO
    "[ru.ticketcraft]": INFO
    "[org.hibernate.SQL]": OFF
    "[org.hibernate.orm.jdbc.bind]": OFF
