spring:
  datasource:
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}

    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:30}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:3000}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    producer:
      retries: ${KAFKA_PRODUCER_RETRIES:10}

catalog:
  service:
    url: ${CATALOG_SERVICE_URL}

ticketcraft:
  kafka:
    consumer:
      concurrency: ${ORDER_KAFKA_CONCURRENCY:3}

    topic:
      partitions: ${KAFKA_TOPIC_PARTITIONS:3}
      replicas: ${KAFKA_TOPIC_REPLICAS:3}

logging:
  level:
    root: INFO
    "[ru.ticketcraft]": INFO
    "[org.hibernate.SQL]": OFF
    "[org.hibernate.orm.jdbc.bind]": OFF
